import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
    'https://qgkvkjjtgrrikknbxkvf.supabase.co',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFna3Zramp0Z3JyaWtrbmJ4a3ZmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjMzMzQwNywiZXhwIjoyMDkxOTA5NDA3fQ.vc8q_1lrVxuKtSgA99kveS2A3vEPD59-JKwV6qTPcX0'
);

async function setup() {
    console.log('Creating tables...');

    // Create spins table
    const { error: e1 } = await supabase.rpc('exec_sql', {
        query: `CREATE TABLE IF NOT EXISTS spins (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            wallet TEXT NOT NULL,
            amount NUMERIC NOT NULL,
            is_win BOOLEAN NOT NULL,
            type TEXT,
            tx_signature TEXT UNIQUE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
        );`
    });

    if (e1) {
        console.log('spins via rpc failed, trying direct...', e1.message);
        // Try using the SQL endpoint directly
        const res = await fetch('https://qgkvkjjtgrrikknbxkvf.supabase.co/rest/v1/rpc/exec_sql', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFna3Zramp0Z3JyaWtrbmJ4a3ZmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjMzMzQwNywiZXhwIjoyMDkxOTA5NDA3fQ.vc8q_1lrVxuKtSgA99kveS2A3vEPD59-JKwV6qTPcX0',
                'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFna3Zramp0Z3JyaWtrbmJ4a3ZmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjMzMzQwNywiZXhwIjoyMDkxOTA5NDA3fQ.vc8q_1lrVxuKtSgA99kveS2A3vEPD59-JKwV6qTPcX0'
            },
            body: JSON.stringify({ query: 'SELECT 1' })
        });
        console.log('Direct REST status:', res.status, await res.text());
    } else {
        console.log('✅ spins table created!');
    }

    // Create server_state table
    const { error: e2 } = await supabase.rpc('exec_sql', {
        query: `CREATE TABLE IF NOT EXISTS server_state (
            id INT PRIMARY KEY,
            seed TEXT NOT NULL
        );`
    });

    if (e2) {
        console.log('server_state via rpc failed:', e2.message);
    } else {
        console.log('✅ server_state table created!');
    }

    // Test: try inserting into tables directly to see if they exist
    console.log('\nTesting if tables exist...');
    const { data: d1, error: te1 } = await supabase.from('spins').select('id').limit(1);
    console.log('spins table:', te1 ? `❌ ${te1.message}` : '✅ exists');

    const { data: d2, error: te2 } = await supabase.from('server_state').select('id').limit(1);
    console.log('server_state table:', te2 ? `❌ ${te2.message}` : '✅ exists');
}

setup();
